### ISSUE TITLE
What type of top-1 accuracy did you report?

### ISSUE THREAD

**Issue by kyj93790** [LeapLabTHU/SimPro#1]
Hello,
thank you for your work and the open source code!

Besides, when reporting top-1 accuracy,
I'm curious if it is based on the performance of **the last epoch**, **the best performance** among all previous epochs, or the **average performance of the last 20 epochs**.

Thank you!

**Comment by Andy-Du20** [comment]
Hello,

Thank you for your question and for your interest in our work!

Regarding the top-1 accuracy, we report the best performance achieved among all previous epochs. To ensure a fair comparison, our experimental setup strictly follows the ACR, which also reports the highest accuracy recorded in the accuracy log.

Please feel free to reach out if you have any further questions.
